### ISSUE TITLE
빨리빨리하세욧!

### ISSUE THREAD

**Issue by dntjr031** [FinalProjectTeam2/portal#111]
- [x] 회원 등록시 관리페이지로 수정 - 완료
- [x] 강의관리, 학부관리 - 재현
- [x] 게시판 수정 잘안되는거 수정 - 우석
- [x] 채팅방 max-width 조정 - 우석
- [x] 게시판 메인에 usage='N'인거 안띄우게 하기, is_private='Y' 비밀글인거 띄우지 않기 - 우석
- [x] 하단 건의사항에 클릭아이콘 넣기 - 우석
- [x] 게시물 수정시 파일 삭제에 컨펌주기 - 우석
- [x] 전화번호 검색페이지 사이드바 포털사이드바로 바꾸기 - 희나
- [x] 학사일정에 링크 달기 - 슬난
- [x] 강의시간 설정에서 수업 없을때 오류 잡기 - 박철
- [x] 강의계획서 업로드창 디자인 수정 - 박철
- [x] 성적입력에서 처음에 목록 안뜨고 셀렉트에 (선택..)추가 - 박철
- [x] 수강생 연락처 처음에 목록 안뜨고 셀렉트에 (선택..)추가 - 박철
- [x] 수강신청에서 처음 셀렉트 잘 나오게 수정 - 박철
- [x] 수강신청에서 학부만 선택시 오류 수정 - 박철
- [x] 과제등록 기능 추가  - 박철
- [x] 강의실 엑셀작업 - 슬난
- [x] 쪽지에 주소록 추가 - 우석

**Comment by dntjr031** [comment]
게시판 수정 잘안되는거 수정 - 완료
채팅방 max-width 조정 - 완료
하단 건의사항에 클릭아이콘 넣기 - 완료
 게시물 수정시 파일 삭제에 컨펌주기 - 완료
쪽지에 주소록 추가 - 완료

**Comment by heenaShin** [comment]
board_Main - 완료
전화번호 검색 portalSideBar 링트 - 완료

**Comment by fe5882** [comment]
10, 12, 13완

**Comment by fe5882** [comment]
14,15완

**Comment by fe5882** [comment]
완
